server {
    listen 80;
    server_name localhost;

    # ОБОВ'ЯЗКОВО: Внутрішній DNS-сервер Docker. Без нього змінні в proxy_pass не працюють!
    resolver 127.0.0.11 valid=5s;

    location / {
        # Записуємо адресу у змінну (прибираємо порт з назви хоста)
        set $upstream_app web;
        
        # Передаємо змінну з портом
        proxy_pass http://$upstream_app:8000;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}


# upstream django_app {
#     server web:8000;
# }

# server {
#     listen 80;
#     # server_name localhost; # або ваш домен
#     server_name 192.168.0.109;

#     location / {
#         # proxy_pass http://web:8000;
#         proxy_pass http://django_app;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
#     }
# }


# server {
#     listen 80;
#     # server_name yourdomain.com ://yourdomain.com; # Вкажіть свій домен або IP-адресу сервера
#     server_name 192.168.0.109; # Замість домену вкажіть вашу IP

#     # Роздача статичних файлів Django
#     location /static/ {
#         alias /app/staticfiles/;
#     }

#     # Проксування запитів на Gunicorn
#     location / {
#         proxy_pass http://django_app;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header Host $http_host;
#         proxy_redirect off;
#     }
# }


