"""
Django settings for clientsmanag project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import logging

# Коренева директорія застосунку
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Загружаем переменные из файла .env
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Запис логу в файл
LOG_FILE = os.path.join(BASE_DIR, "server_log.txt")
logging.basicConfig(
    filename=LOG_FILE,
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    encoding="utf-8"
)
logging.info(f"--- ЗЧИТУВАННЯ ПОТОЧНИХ НАЛАШТУВАННЯ З SETTINGS: ---") 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEFAULT_SECRET_KEY = "django-insecure-h#=rcxc2ejw)3p628s8p47(_&59-a$v^%8pjo!v#n@t)*#we)*"
SECRET_KEY = os.getenv("SECRET_KEY", DEFAULT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", False)
# DEBUG = True
# DEBUG = False
logging.info(f"Поточні налаштування: DEBUG = {DEBUG}") 

ALLOWED_HOSTS_STR = os.getenv("ALLOWED_HOSTS", '*')
ALLOWED_HOSTS = [item.strip() for item in ALLOWED_HOSTS_STR.split(',')]
# ALLOWED_HOSTS = ['127.0.0.1', '192.168.1.200', 'localhost']
# ALLOWED_HOSTS = ['*']
# print(ALLOWED_HOSTS)
logging.info(f"Поточні налаштування: ALLOWED_HOSTS = {ALLOWED_HOSTS}") 


# CSRF_TRUSTED_ORIGINS = [
#     'http://ishome.net:8282',
#     'http://localhost:8282', # Опционально для локальной разработки
# ]
CSRF_TRUSTED_ORIGINS_STR = os.getenv("CSRF_TRUSTED_ORIGINS", '*')
CSRF_TRUSTED_ORIGINS = [item.strip() for item in CSRF_TRUSTED_ORIGINS_STR.split(',')]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    'django_select2',
    # "phone_field",
    "clients.apps.ClientsConfig",
    "accounts.apps.AccountsConfig",
    "finances.apps.FinancesConfig",
    "logs.apps.LogsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "clients.middleware.PermissionDeniedErrorHandler",
    "clients.middleware.RequestMiddleware",
]

ROOT_URLCONF = "clientsmanag.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "clientsmanag.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Зчитуємо нові параметри з файлу налаштуваннь
DB_TYPE=os.getenv("DB_TYPE", 'sqlite')
logging.info(f"Поточні налаштування: DB_TYPE = {DB_TYPE}") 

if DB_TYPE=='sqlite':
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / 'db.sqlite3',
        }
    }

elif DB_TYPE=='mysql':
    MYSQL_DATABASE=os.getenv("MYSQL_DATABASE", 'msqldb1')
    MYSQL_USER=os.getenv("MYSQL_USER", '')
    MYSQL_PASSWORD=os.getenv("MYSQL_PASSWORD", '')
    MYSQL_HOST = os.getenv("MYSQL_HOST", "localhost")
    MYSQL_PORT = os.getenv("MYSQL_PORT", "3306")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            'NAME': MYSQL_DATABASE,
            'USER': MYSQL_USER,
            'PASSWORD': MYSQL_PASSWORD,
            'HOST': MYSQL_HOST,
            'PORT': MYSQL_PORT,
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
    logging.info(f"Поточні налаштування: DB_NAME = {MYSQL_DATABASE}") 
    logging.info(f"Поточні налаштування: DB_HOST:DB_PORT = {MYSQL_HOST}:{MYSQL_PORT}") 


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "uk"

# TIME_ZONE = "UTC"
# TIME_ZONE = "Europe/Kiev"
TIME_ZONE = 'Europe/Kyiv'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "clientsmanag/static"),
]
# Увімкнення стиснення та кешування
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

USE_REDIS = os.getenv("USE_REDIS", "True") == "True"
# USE_REDIS = os.getenv("USE_REDIS", "True")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": os.path.join(BASE_DIR, "django_cache"),
    },
    "select2": {
        "BACKEND": "django_redis.cache.RedisCache" if USE_REDIS else "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "redis://redis:6379/2" if USE_REDIS else "select2-local-cache",
    }
}
if USE_REDIS:
    CACHES["select2"]["OPTIONS"] = {"CLIENT_CLASS": "django_redis.client.DefaultClient"}

SELECT2_CACHE_BACKEND = "select2"

LOGIN_REDIRECT_URL = '/'

if os.environ.get('DEBUG', 'True') == 'False':
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }

