# Generated by Django 5.2 on 2025-06-01 08:44

import django.db.models.deletion
import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('data', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва клієнта')),
                ('fullname', models.CharField(max_length=255, verbose_name='Повна назва клієнта')),
                ('code', models.IntegerField(blank=True, default=0, verbose_name='Код ЄДРПОУ')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('comment', models.TextField(blank=True, verbose_name='Коммент')),
                ('type', models.IntegerField(default=1, verbose_name='Тип')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True, verbose_name='Url')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва компа')),
                ('app', models.IntegerField(default=0)),
                ('idinapp', models.IntegerField(default=0)),
                ('passinapp', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=1)),
                ('comment', models.TextField(blank=True, verbose_name='Коммент')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='clients.client')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ПІБ')),
                ('phone1', phone_field.models.PhoneField(blank=True, help_text='Контактний телефон (1): ', max_length=31)),
                ('phone2', phone_field.models.PhoneField(blank=True, help_text='Контактний телефон (1): ', max_length=31)),
                ('phone3', phone_field.models.PhoneField(blank=True, help_text='Контактний телефон (1): ', max_length=31)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Посада')),
                ('order', models.IntegerField(default=1, verbose_name='Порядок показу')),
                ('comment', models.TextField(blank=True, verbose_name='Коммент')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='clients.client')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clients', to='clients.tag'),
        ),
    ]
