# Generated by Django 5.2 on 2025-06-01 17:29

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'ordering': ['name'], 'verbose_name': 'Доступ', 'verbose_name_plural': 'Доступи'},
        ),
        migrations.AlterModelOptions(
            name='add_data',
            options={'ordering': ['title'], 'verbose_name': 'Додаткові дані', 'verbose_name_plural': 'Додаткові дані'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Клієнт(a)', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакти'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='access',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва компа'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=phone_field.models.PhoneField(blank=True, help_text='Вкажіть контактний телефон у форматі (415) 123-4567. ', max_length=31),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=phone_field.models.PhoneField(blank=True, help_text='Вкажіть контактний телефон у форматі (415) 123-4567. ', max_length=31),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone3',
            field=phone_field.models.PhoneField(blank=True, help_text='Вкажіть контактний телефон у форматі (415) 123-4567. ', max_length=31),
        ),
    ]
