# Generated by Django 5.2 on 2025-06-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_access_options_alter_add_data_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='app',
            field=models.CharField(max_length=100, verbose_name='Застосунок для доступу'),
        ),
        migrations.AlterField(
            model_name='access',
            name='idinapp',
            field=models.IntegerField(blank=True, verbose_name='ID в застосунку'),
        ),
        migrations.AlterField(
            model_name='access',
            name='passinapp',
            field=models.IntegerField(blank=True, verbose_name='Пароль'),
        ),
    ]
