# Generated by Django 5.2 on 2025-06-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_access_app_alter_access_idinapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='passinapp',
            field=models.CharField(blank=True, max_length=255, verbose_name='Пароль'),
        ),
    ]
