# Generated by Django 5.2 on 2025-06-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_access_passinapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='idinapp',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID в застосунку'),
        ),
    ]
