# Generated by Django 5.2 on 2025-06-02 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_access_idinapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Введите номер телефона в формате +ХХХ XX XXX-XX-XX', regex='^\\+?\\d{1,4}?\\s?\\d{1,14}\\s?\\d{1,14}$')]),
        ),
    ]
