# Generated by Django 5.2 on 2025-06-04 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_contact_phone1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_data',
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.IntegerField(choices=[(0, 'my_org'), (1, 'client'), (2, 'partner')], default=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Вкажіть контактний телефон у форматі +ХХХ XX XXX-XX-XX', regex='^\\+?\\d{1,4}?\\s?\\d{1,14}\\s?\\d{1,14}$')]),
        ),
    ]
