# Generated by Django 5.2 on 2025-06-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_delete_add_data_alter_client_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='access',
            name='app',
            field=models.CharField(choices=[('AD', 'AnyDesk'), ('AA', 'Ammy Admin'), ('TV', 'Team Viewer'), ('RDP', 'Remote Desktop Protocol')], max_length=100, verbose_name='Застосунок для доступу'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.IntegerField(blank=True, verbose_name='Код ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.IntegerField(choices=[(0, 'my_org'), (1, 'клієнт'), (2, 'партнер')], default=1, verbose_name='Тип'),
        ),
    ]
