# Generated by Django 5.2 on 2025-06-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_tag_color_alter_access_app_alter_client_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.IntegerField(blank=True, default=0, verbose_name='Код ЄДРПОУ'),
        ),
    ]
