# Generated by Django 5.2 on 2025-06-09 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-pk'], 'verbose_name': 'Клієнт(a)', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Вкажіть контактний телефон у форматі +ХХХ XX XXX-XX-XX', regex='^\\+?\\d{1,4}?\\s?\\d{1,14}\\s?\\d{1,14}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone3',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Вкажіть контактний телефон у форматі +ХХХ XX XXX-XX-XX', regex='^\\+?\\d{1,4}?\\s?\\d{1,14}\\s?\\d{1,14}$')]),
        ),
    ]
