# Generated by Django 5.2 on 2025-06-17 01:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_client_options_alter_contact_phone2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='app',
            field=models.CharField(choices=[('AD', 'AnyDesk'), ('AA', 'Ammy Admin'), ('TV', 'Team Viewer'), ('RDP', 'Remote Desktop Protocol'), ('Other', 'Other app')], max_length=100, verbose_name='Застосунок для доступу'),
        ),
        migrations.AlterField(
            model_name='access',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='clients.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='access',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='clients.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Вкажіть контактний телефон у форматі +380 XX XXX-XX-XX', regex='^\\+?\\d{1,4}?\\s?\\d{1,14}\\s?\\d{1,14}$')], verbose_name='Телефон 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Вкажіть контактний телефон у форматі +380 XX XXX-XX-XX', regex='^\\+?\\d{1,4}?\\s?\\d{1,14}\\s?\\d{1,14}$')], verbose_name='Телефон 2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone3',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Вкажіть контактний телефон у форматі +380 XX XXX-XX-XX', regex='^\\+?\\d{1,4}?\\s?\\d{1,14}\\s?\\d{1,14}$')], verbose_name='Телефон 3'),
        ),
        migrations.CreateModel(
            name='Islog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_model', models.CharField(max_length=100, verbose_name='obj_model')),
                ('obj_id', models.IntegerField(default=0, verbose_name='obj_id')),
                ('mess', models.TextField(blank=True)),
                ('action_tag', models.IntegerField(choices=[(1, 'add'), (2, 'edit'), (3, 'delete')], default=0, verbose_name='action_tag')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['date_time'],
            },
        ),
    ]
