# Generated by Django 5.2 on 2025-06-17 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_access_app_alter_access_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='islog',
            old_name='user_id',
            new_name='user',
        ),
    ]
