# Generated by Django 5.2 on 2025-06-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_rename_user_id_islog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='islog',
            name='app_label',
            field=models.CharField(default='clients', max_length=100, verbose_name='app_label'),
        ),
    ]
