# Generated by Django 5.2 on 2025-07-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_islog_app_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Islog',
        ),
    ]
