# Generated by Django 5.2 on 2026-01-03 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_delete_islog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citydistr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Назва района міста')),
            ],
            options={
                'verbose_name': 'Район міста',
                'verbose_name_plural': 'Райони міста',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва міста/села')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Поселення',
                'verbose_name_plural': 'Поселення',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Назва'),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('fullname', models.CharField(max_length=255, verbose_name='Повна назва')),
                ('archive', models.BooleanField(default=False, verbose_name='Архівний')),
                ('citydistr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='streets', to='clients.citydistr', verbose_name='Район міста')),
            ],
            options={
                'verbose_name': 'Вулиця',
                'verbose_name_plural': 'Вулиці',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fulladdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresstype', models.IntegerField(default=1, verbose_name='Тип адреси')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='Індекс')),
                ('country', models.IntegerField(default=1, verbose_name='Країна')),
                ('region', models.IntegerField(blank=True, null=True, verbose_name='Область')),
                ('settltype', models.IntegerField(blank=True, null=True, verbose_name='тип населенного пункту')),
                ('streettype', models.IntegerField(blank=True, null=True, verbose_name='тип вулиці')),
                ('housenum', models.CharField(blank=True, max_length=10, verbose_name='Номер будиноку')),
                ('apartmenttype', models.IntegerField(blank=True, null=True, verbose_name='тип квартира/офіс')),
                ('apartment', models.IntegerField(blank=True, null=True, verbose_name='Номер квартири')),
                ('entrance', models.IntegerField(blank=True, null=True, verbose_name="Під'їзд")),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Поверх')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коммент')),
                ('citydistr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulladdress', to='clients.citydistr', verbose_name='Район міста')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulladdresses', to='clients.client', verbose_name='Клієнт')),
                ('settlname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulladdress', to='clients.settlement', verbose_name='Населенний пункт')),
                ('oldstreetname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulladdress', to='clients.street', verbose_name='назва вулиці')),
                ('streetname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='clients.street', verbose_name='назва вулиці')),
            ],
            options={
                'verbose_name': 'Адреса',
                'verbose_name_plural': 'Адреси',
                'ordering': ['streetname'],
            },
        ),
    ]
