# Generated by Django 5.2 on 2026-01-04 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_citydistr_settlement_alter_tag_color_alter_tag_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settlement',
            new_name='City',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'Місто', 'verbose_name_plural': 'Міста'},
        ),
        migrations.RemoveField(
            model_name='fulladdress',
            name='settlname',
        ),
        migrations.AddField(
            model_name='fulladdress',
            name='cityname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulladdress', to='clients.city', verbose_name='Назва міста/села'),
        ),
    ]
