# Generated by Django 5.2 on 2026-01-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_rename_settlement_city_alter_city_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citydistr',
            new_name='Distr',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-pk'], 'verbose_name': 'Клієнт', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.RenameField(
            model_name='fulladdress',
            old_name='citydistr',
            new_name='distr',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='citydistr',
            new_name='distr',
        ),
    ]
