# Generated by Django 5.2 on 2026-01-09 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_rename_citydistr_distr_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коммент'),
        ),
        migrations.AlterField(
            model_name='fulladdress',
            name='addresstype',
            field=models.IntegerField(choices=[(1, 'юридична'), (2, 'фактична'), (3, 'офіс'), (9, 'інша')], default=1, verbose_name='Тип адреси'),
        ),
        migrations.AlterField(
            model_name='fulladdress',
            name='apartmenttype',
            field=models.IntegerField(blank=True, choices=[(0, '-----.'), (1, 'кв.'), (2, 'оф.'), (3, 'ін.')], null=True, verbose_name='тип квартира/офіс'),
        ),
        migrations.AlterField(
            model_name='fulladdress',
            name='country',
            field=models.IntegerField(choices=[(0, 'не вказана'), (1, 'Україна')], default=1, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='fulladdress',
            name='oldstreetname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulladdress', to='clients.street', verbose_name='Стара назва вулиці'),
        ),
        migrations.AlterField(
            model_name='fulladdress',
            name='region',
            field=models.IntegerField(blank=True, choices=[(0, 'не вказана'), (1, 'Вінницька область'), (2, 'Волинська область'), (3, 'Дніпропетровська область'), (4, 'Донецька область'), (5, 'Житомирська область'), (6, 'Закарпатська область'), (7, 'Запорізька область'), (8, 'Івано-Франківська область'), (9, 'Київська область'), (10, 'Кіровоградська область'), (11, 'Луганська область'), (12, 'Львівська область'), (13, 'Миколаївська область'), (14, 'Одеська область'), (15, 'Полтавська область'), (16, 'Рівненська область'), (17, 'Сумська область'), (18, 'Тернопільська область'), (19, 'Харківська область'), (20, 'Херсонська область'), (21, 'Хмельницьцка область'), (22, 'Черкаська область'), (23, 'Чернівецька область'), (24, 'Чернігівська область'), (25, 'АР Крим')], null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='fulladdress',
            name='settltype',
            field=models.IntegerField(blank=True, choices=[(0, '-----'), (1, 'м.'), (2, 'с.'), (3, 'смт.')], null=True, verbose_name='Тип населенного пункту'),
        ),
        migrations.AlterField(
            model_name='fulladdress',
            name='streetname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='clients.street', verbose_name='Назва вулиці'),
        ),
        migrations.AlterField(
            model_name='fulladdress',
            name='streettype',
            field=models.IntegerField(blank=True, choices=[(0, '-----'), (1, 'вул.'), (2, 'просп.'), (3, 'пров.'), (4, 'пл.')], null=True, verbose_name='Тип вулиці'),
        ),
    ]
