# Generated by Django 5.2 on 2026-01-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_client_address_alter_client_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='settltype',
            field=models.IntegerField(blank=True, choices=[(0, '-----'), (1, 'м.'), (2, 'с.'), (3, 'смт.')], null=True, verbose_name='Тип населенного пункту'),
        ),
    ]
