# Generated by Django 5.2 on 2026-01-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_city_settltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='fullname',
        ),
        migrations.AddField(
            model_name='street',
            name='streettype',
            field=models.IntegerField(blank=True, choices=[(0, '-----'), (1, 'вул.'), (2, 'просп.'), (3, 'пров.'), (4, 'пл.')], null=True, verbose_name='Тип вулиці'),
        ),
    ]
