# Generated by Django 5.2 on 2026-01-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_remove_street_fullname_street_streettype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulladdress',
            name='settltype',
        ),
        migrations.RemoveField(
            model_name='fulladdress',
            name='streettype',
        ),
    ]
