# Generated by Django 5.2 on 2026-03-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_remove_fulladdress_settltype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='clients', to='clients.tag', verbose_name='Тег'),
        ),
    ]
