# Generated by Django 5.2 on 2026-03-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_alter_client_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='clients', to='clients.tag', verbose_name='Теги'),
        ),
    ]
