# Generated by Django 5.2 on 2026-06-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_alter_client_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код ЄДРПОУ'),
        ),
    ]
