# Generated by Django 5.2 on 2026-07-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_alter_client_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remoteapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Застосунок для доступу',
                'verbose_name_plural': 'Застосунок для доступу',
                'ordering': ['name'],
            },
        ),
    ]
