# Generated by Django 5.2 on 2026-07-09 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_alter_access_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='clients.remoteapp', verbose_name='Застосунок для доступу'),
        ),
    ]
