# Generated by Django 5.2 on 2025-07-11 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Islog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(default='clients', max_length=100, verbose_name='app_label')),
                ('obj_model', models.CharField(max_length=100, verbose_name='obj_model')),
                ('obj_id', models.IntegerField(default=0, verbose_name='obj_id')),
                ('mess', models.TextField(blank=True)),
                ('action_tag', models.IntegerField(choices=[(1, 'add'), (2, 'edit'), (3, 'delete')], default=0, verbose_name='action_tag')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['date_time'],
            },
        ),
    ]
