# Generated by Django 5.2 on 2025-07-07 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0013_islog_app_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('fullname', models.CharField(max_length=255, verbose_name='Повна назва')),
                ('code', models.IntegerField(blank=True, verbose_name='Код')),
                ('type', models.IntegerField(choices=[(1, 'ліцензія'), (2, 'послуга'), (3, 'товар')], default=1, verbose_name='Тип')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('tag', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='nomenclatures', to='clients.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
                'ordering': ['pk'],
            },
        ),
    ]
