# Generated by Django 5.2 on 2025-07-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_delete_islog'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nomenclatures', to='clients.tag', verbose_name='Тег'),
        ),
    ]
