# Generated by Django 5.2 on 2025-07-21 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_nomenclature_code_alter_nomenclature_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='Ціна')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='finances.nomenclature', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайси',
                'ordering': ['pk'],
            },
        ),
    ]
