# Generated by Django 5.2 on 2025-07-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
    ]
