# Generated by Django 5.2 on 2025-08-09 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_delete_islog'),
        ('finances', '0004_alter_price_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0, verbose_name='Знижка')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='clients.client', verbose_name='Кліент')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайси',
                'ordering': ['pk'],
            },
        ),
    ]
