# Generated by Django 5.2 on 2025-08-19 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_delete_islog'),
        ('finances', '0005_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ['pk'], 'verbose_name': 'Баланс', 'verbose_name_plural': 'Баланс'},
        ),
        migrations.AlterModelOptions(
            name='nomenclature',
            options={'ordering': ['name'], 'verbose_name': 'Номенклатура', 'verbose_name_plural': 'Номенклатура'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['nomenclature'], 'verbose_name': 'Прайс', 'verbose_name_plural': 'Прайси'},
        ),
        migrations.RemoveField(
            model_name='balance',
            name='discount',
        ),
        migrations.AddField(
            model_name='balance',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance', to='clients.client', verbose_name='Кліент'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(default=0, verbose_name='Знижка')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount', to='clients.client', verbose_name='Кліент')),
            ],
            options={
                'verbose_name': 'Знижка',
                'verbose_name_plural': 'Знижки',
                'ordering': ['pk'],
            },
        ),
    ]
