# Generated by Django 5.2 on 2025-08-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_alter_balance_options_alter_nomenclature_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='date_time',
            new_name='datetime',
        ),
    ]
