# Generated by Django 5.2 on 2026-01-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_rename_date_time_price_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['client'], 'verbose_name': 'Знижка', 'verbose_name_plural': 'Знижки'},
        ),
    ]
