# Generated by Django 5.2 on 2026-03-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_remove_fulladdress_settltype_and_more'),
        ('finances', '0008_alter_discount_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('datedoc', models.DateField(verbose_name='Дата')),
                ('sum', models.IntegerField(default=0, verbose_name='Сума')),
                ('paytype', models.IntegerField(choices=[(1, 'обігові кошти'), (2, 'через розрахунковий рахунок')], default=1, verbose_name='Тип платежу')),
                ('paystatus', models.IntegerField(choices=[(0, 'не проведено'), (1, 'проведено')], default=1, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар (призначення платежу)')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payeecashbooks', to='clients.client', verbose_name='Отримувач')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payercashbooks', to='clients.client', verbose_name='Платник')),
            ],
            options={
                'verbose_name': 'Кассова книга',
                'verbose_name_plural': 'Кассові книги',
                'ordering': ['pk'],
            },
        ),
    ]
