# Generated by Django 5.2 on 2026-03-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_cashbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='paytype',
            field=models.IntegerField(choices=[(1, 'безготівковий'), (2, 'готівковий')], default=1, verbose_name='Тип платежу'),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума'),
        ),
    ]
