# Generated by Django 5.2 on 2026-03-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_alter_cashbook_paytype_alter_cashbook_sum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbook',
            options={'ordering': ['-datedoc'], 'verbose_name': 'Платіж', 'verbose_name_plural': 'Платежі'},
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='paystatus',
            field=models.IntegerField(choices=[(1, 'проведено'), (2, 'не проведено')], default=1, verbose_name='Статус'),
        ),
    ]
