# Generated by Django 5.2 on 2026-03-24 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_client_tags'),
        ('finances', '0011_alter_cashbook_options_alter_cashbook_paystatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Date time')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sum')),
                ('docapp', models.CharField(default='finances', max_length=100, verbose_name='doc_app')),
                ('docmodel', models.CharField(max_length=100, verbose_name='doc_model')),
                ('docid', models.IntegerField(default=0, verbose_name='doc_id')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transaction',
                'ordering': ['-pk'],
            },
        ),
    ]
