# Generated by Django 5.2 on 2026-03-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-pk'], 'verbose_name': 'Операція', 'verbose_name_plural': 'Операції'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='balance'),
        ),
    ]
