# Generated by Django 5.2 on 2026-03-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_alter_transaction_options_transaction_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbook',
            options={'ordering': ['-pk'], 'verbose_name': 'Платіж', 'verbose_name_plural': 'Платежі'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='datedoc',
            field=models.DateField(default='2026-01-01', verbose_name='Дата'),
        ),
    ]
