# Generated by Django 5.2 on 2026-03-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_alter_cashbook_options_transaction_datedoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='datedoc',
            new_name='docdate',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='balance',
        ),
    ]
