# Generated by Django 5.2 on 2026-04-07 05:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_client_tags'),
        ('finances', '0015_rename_datedoc_transaction_docdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='datedoc',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price')),
                ('orderdate', models.DateField(default=datetime.date.today, verbose_name='orderdate')),
                ('enddate', models.DateField(verbose_name='enddate')),
                ('pccode', models.CharField(blank=True, max_length=100, null=True, verbose_name='pccode')),
                ('licensecode', models.CharField(blank=True, max_length=255, null=True, verbose_name='licensecode')),
                ('devdiscount', models.IntegerField(default=0, verbose_name='devdiscount')),
                ('devprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='devprice')),
                ('agdiscount', models.IntegerField(default=0, verbose_name='agdiscount')),
                ('agprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='agprice')),
                ('taxdiscount', models.IntegerField(default=0, verbose_name='taxdiscount')),
                ('taxprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='taxprice')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agentlicenses', to='clients.client', verbose_name='agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientlicenses', to='clients.client', verbose_name='client')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='developerlicenses', to='clients.client', verbose_name='developer')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='finances.nomenclature', verbose_name='Номенклатура')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sellerlicenses', to='clients.client', verbose_name='seller')),
                ('taxes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxeslicenses', to='clients.client', verbose_name='taxes')),
            ],
            options={
                'verbose_name': 'license',
                'verbose_name_plural': 'licenses',
                'ordering': ['-enddate'],
            },
        ),
    ]
