# Generated by Django 5.2 on 2026-04-15 20:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_alter_client_tags'),
        ('finances', '0016_alter_cashbook_datedoc_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['enddate'], 'verbose_name': 'Ліцензія', 'verbose_name_plural': 'Ліцензії'},
        ),
        migrations.AlterField(
            model_name='license',
            name='agdiscount',
            field=models.IntegerField(default=0, verbose_name='Відсоток Агента'),
        ),
        migrations.AlterField(
            model_name='license',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agentlicenses', to='clients.client', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='license',
            name='agprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата Агенту'),
        ),
        migrations.AlterField(
            model_name='license',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientlicenses', to='clients.client', verbose_name='Кліент'),
        ),
        migrations.AlterField(
            model_name='license',
            name='devdiscount',
            field=models.IntegerField(default=0, verbose_name='Відсоток Розробника'),
        ),
        migrations.AlterField(
            model_name='license',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='developerlicenses', to='clients.client', verbose_name='Розробник'),
        ),
        migrations.AlterField(
            model_name='license',
            name='devprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата Розробнику'),
        ),
        migrations.AlterField(
            model_name='license',
            name='enddate',
            field=models.DateField(verbose_name='Дата закінчення'),
        ),
        migrations.AlterField(
            model_name='license',
            name='licensecode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код ліцензії'),
        ),
        migrations.AlterField(
            model_name='license',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='finances.nomenclature', verbose_name='Ліцензія'),
        ),
        migrations.AlterField(
            model_name='license',
            name='orderdate',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата замовлення'),
        ),
        migrations.AlterField(
            model_name='license',
            name='pccode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код компьютера'),
        ),
        migrations.AlterField(
            model_name='license',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='license',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sellerlicenses', to='clients.client', verbose_name='Постачальник'),
        ),
        migrations.AlterField(
            model_name='license',
            name='taxdiscount',
            field=models.IntegerField(default=0, verbose_name='Відсоток Податку'),
        ),
        migrations.AlterField(
            model_name='license',
            name='taxes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxeslicenses', to='clients.client', verbose_name='Податки'),
        ),
        migrations.AlterField(
            model_name='license',
            name='taxprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата Податку'),
        ),
    ]
