# Generated by Django 5.2 on 2026-07-09 20:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_alter_access_app'),
        ('finances', '0017_alter_license_options_alter_license_agdiscount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('datedoc', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна')),
                ('paytype', models.IntegerField(choices=[(1, 'безготівковий'), (2, 'готівковий')], default=1, verbose_name='Тип платежу')),
                ('paystatus', models.IntegerField(choices=[(1, 'проведено'), (2, 'не проведено')], default=1, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientacts', to='clients.client', verbose_name='Кліент')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomenclatureacts', to='finances.nomenclature', verbose_name='Послуга')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provideracts', to='clients.client', verbose_name='Виконавець')),
            ],
            options={
                'verbose_name': 'Акт',
                'verbose_name_plural': 'Акти',
                'ordering': ['-pk'],
            },
        ),
    ]
