# Generated by Django 5.2 on 2026-07-10 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_alter_access_app'),
        ('finances', '0018_alter_price_datetime_alter_price_price_act'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'ordering': ['-datedoc'], 'verbose_name': 'Акт', 'verbose_name_plural': 'Акти'},
        ),
        migrations.RemoveField(
            model_name='act',
            name='paystatus',
        ),
        migrations.RemoveField(
            model_name='act',
            name='paytype',
        ),
        migrations.RemoveField(
            model_name='act',
            name='provider',
        ),
        migrations.AddField(
            model_name='act',
            name='agdiscount',
            field=models.IntegerField(default=0, verbose_name='Відсоток Виконавець'),
        ),
        migrations.AddField(
            model_name='act',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agentacts', to='clients.client', verbose_name='Виконавець'),
        ),
        migrations.AddField(
            model_name='act',
            name='agprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата Виконавець'),
        ),
        migrations.AddField(
            model_name='act',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selleracts', to='clients.client', verbose_name='Постачальник'),
        ),
        migrations.AddField(
            model_name='act',
            name='taxdiscount',
            field=models.IntegerField(default=0, verbose_name='Відсоток Податку'),
        ),
        migrations.AddField(
            model_name='act',
            name='taxes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxesacts', to='clients.client', verbose_name='Податки'),
        ),
        migrations.AddField(
            model_name='act',
            name='taxprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата Податку'),
        ),
    ]
