# Generated by Django 5.2 on 2026-07-10 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0028_alter_access_app'),
        ('finances', '0019_alter_act_options_remove_act_paystatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='agdiscount',
            field=models.IntegerField(default=0, verbose_name='Відсоток Підрядник'),
        ),
        migrations.AlterField(
            model_name='act',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agentacts', to='clients.client', verbose_name='Підрядник'),
        ),
        migrations.AlterField(
            model_name='act',
            name='agprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата Підрядник'),
        ),
        migrations.AlterField(
            model_name='act',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientacts', to='clients.client', verbose_name='Замовник'),
        ),
        migrations.AlterField(
            model_name='act',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selleracts', to='clients.client', verbose_name='Виконавець'),
        ),
    ]
